### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by vnnimbalkar**

### CODE REVIEW

**Comment by atlantis-vm** [comment]
Ran Plan for dir: `prj-01/components/vm` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
+ resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + effective_labels     = (known after apply)
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-micro"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "vm-from-prj-01"
      + project              = "upheld-rain-404605"
      + self_link            = (known after apply)
      + tags                 = [
          + "dev",
          + "engineering",
        ]
      + tags_fingerprint     = (known after apply)
      + terraform_labels     = (known after apply)
      + zone                 = "us-central1-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image                  = "debian-cloud/debian-11"
              + labels                 = {
                  + "env" = "dev"
                }
              + provisioned_iops       = (known after apply)
              + provisioned_throughput = (known after apply)
              + size                   = (known after apply)
              + type                   = (known after apply)
            }
        }

      + network_interface {
          + internal_ipv6_prefix_length = (known after apply)
          + ipv6_access_type            = (known after apply)
          + ipv6_address                = (known after apply)
          + name                        = (known after apply)
          + network                     = "default"
          + network_ip                  = (known after apply)
          + stack_type                  = (known after apply)
          + subnetwork                  = (known after apply)
          + subnetwork_project          = (known after apply)

          + access_config {
              + nat_ip       = (known after apply)
              + network_tier = (known after apply)
            }
        }
    }

  # google_storage_bucket.auto-expire will be created
+ resource "google_storage_bucket" "auto-expire" {
      + effective_labels            = (known after apply)
      + force_destroy               = true
      + id                          = (known after apply)
      + location                    = "US"
      + name                        = "Prj-01-Bucket"
      + project                     = (known after apply)
      + public_access_prevention    = "enforced"
      + rpo                         = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + terraform_labels            = (known after apply)
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d prj-01/components/vm`
* :put_litter_in_its_place: To **delete** this plan click [here](http://35.223.70.45/lock?id=atlantis-vm%252Ffoundation%252Fprj-01%252Fcomponents%252Fvm%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d prj-01/components/vm`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by vnnimbalkar** [comment]
atlantis apply

**Comment by atlantis-vm** [comment]
Ran Apply for dir: `prj-01/components/vm` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/root/.atlantis/repos/atlantis-vm/foundation/2/default/prj-01/components/vm/default.tfplan\"" in "/root/.atlantis/repos/atlantis-vm/foundation/2/default/prj-01/components/vm": exit status 1
google_storage_bucket.auto-expire: Creating...
google_compute_instance.default: Creating...
google_compute_instance.default: Still creating... [10s elapsed]
google_compute_instance.default: Still creating... [20s elapsed]
google_compute_instance.default: Creation complete after 23s [id=projects/upheld-rain-404605/zones/us-central1-a/instances/vm-from-prj-01]
╷
│ Error: error: bucket name validation failed Prj-01-Bucket. See https://cloud.google.com/storage/docs/naming-buckets
│ 
│   with google_storage_bucket.auto-expire,
│   on main.tf line 30, in resource "google_storage_bucket" "auto-expire":
│   30: resource "google_storage_bucket" "auto-expire" {
│ 
╵

```
</details>

**Comment by atlantis-vm** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `prj-01/components/vm` workspace: `default`

**Comment by atlantis-vm** [comment]
Ran Plan for dir: `prj-01/components/vm` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/upheld-rain-404605/zones/us-central1-a/instances/vm-from-prj-01]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_storage_bucket.auto-expire will be created
+ resource "google_storage_bucket" "auto-expire" {
      + effective_labels            = (known after apply)
      + force_destroy               = true
      + id                          = (known after apply)
      + location                    = "US"
      + name                        = "prj-01-Bucket"
      + project                     = (known after apply)
      + public_access_prevention    = "enforced"
      + rpo                         = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + terraform_labels            = (known after apply)
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d prj-01/components/vm`
* :put_litter_in_its_place: To **delete** this plan click [here](http://35.223.70.45/lock?id=atlantis-vm%252Ffoundation%252Fprj-01%252Fcomponents%252Fvm%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d prj-01/components/vm`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by vnnimbalkar** [comment]
atlantis apply

**Comment by atlantis-vm** [comment]
Ran Apply for dir: `prj-01/components/vm` workspace: `default`

**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/root/.atlantis/repos/atlantis-vm/foundation/2/default/prj-01/components/vm/default.tfplan\"" in "/root/.atlantis/repos/atlantis-vm/foundation/2/default/prj-01/components/vm": exit status 1
google_storage_bucket.auto-expire: Creating...
╷
│ Error: error: bucket name validation failed prj-01-Bucket. See https://cloud.google.com/storage/docs/naming-buckets
│ 
│   with google_storage_bucket.auto-expire,
│   on main.tf line 30, in resource "google_storage_bucket" "auto-expire":
│   30: resource "google_storage_bucket" "auto-expire" {
│ 
╵

```

**Comment by atlantis-vm** [comment]
Ran Plan for dir: `prj-01/components/vm` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/upheld-rain-404605/zones/us-central1-a/instances/vm-from-prj-01]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_storage_bucket.auto-expire will be created
+ resource "google_storage_bucket" "auto-expire" {
      + effective_labels            = (known after apply)
      + force_destroy               = true
      + id                          = (known after apply)
      + location                    = "US"
      + name                        = "prj-01-bucket"
      + project                     = (known after apply)
      + public_access_prevention    = "enforced"
      + rpo                         = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + terraform_labels            = (known after apply)
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d prj-01/components/vm`
* :put_litter_in_its_place: To **delete** this plan click [here](http://35.223.70.45/lock?id=atlantis-vm%252Ffoundation%252Fprj-01%252Fcomponents%252Fvm%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d prj-01/components/vm`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by vnnimbalkar** [comment]
atlantis apply

**Comment by atlantis-vm** [comment]
Ran Apply for dir: `prj-01/components/vm` workspace: `default`

```diff
google_storage_bucket.auto-expire: Creating...
google_storage_bucket.auto-expire: Creation complete after 1s [id=prj-01-bucket]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by atlantis-vm** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `prj-01/components/vm` workspace: `default`

**Pull request merged**
